# Generated by Django 4.2.6 on 2023-11-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date on which it was created.', verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Date it was last updated.', verbose_name='updated at')),
                ('email', models.EmailField(max_length=254)),
                ('codigo', models.CharField(max_length=6)),
                ('fecha_vigencia', models.DateTimeField()),
                ('fecha_ultimo_envio', models.DateTimeField(null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('VENCIDO', 'Inactivo'), ('EXITOSO', 'Validado')], default='ACTIVO', max_length=10)),
            ],
            options={
                'verbose_name': 'verificacion_otp',
                'verbose_name_plural': 'verificaciones_otp',
                'db_table': 'codigo_otp',
                'ordering': ['-created', '-updated'],
                'get_latest_by': 'created',
                'abstract': False,
                'managed': True,
            },
        ),
    ]
