# Generated by Django 4.2.6 on 2023-12-01 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_codigootp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCodigoOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date on which it was created.', verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Date it was last updated.', verbose_name='updated at')),
                ('maximo_intentos', models.SmallIntegerField()),
                ('tiempo_bloqueo_usuario', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': 'configuracion_codigo_otp',
                'verbose_name_plural': 'configuracion_codigo_otp',
                'db_table': 'configuracion_codigo_otp',
                'ordering': ['-created', '-updated'],
                'get_latest_by': 'created',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='codigootp',
            name='conteo_intentos',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='codigootp',
            name='maximo_intentos',
            field=models.SmallIntegerField(default=1),
        ),
    ]
