# Generated by Django 4.2.6 on 2023-12-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.TextField(max_length=150, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.TextField(max_length=150, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.TextField(max_length=250, verbose_name='Place'),
        ),
    ]
