# Generated by Django 4.2.6 on 2023-12-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_address_alter_event_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmedia',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
