# Generated by Django 4.2.6 on 2023-12-15 10:32

from django.db import migrations, models
import facetix_api.events.models.events


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventmedia_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='file_cover',
            field=models.FileField(null=True, upload_to=facetix_api.events.models.events.directory_path),
        ),
        migrations.AlterField(
            model_name='eventmedia',
            name='type',
            field=models.CharField(choices=[('1', 'GALLERY'), ('2', 'COVER')], default='1', max_length=1),
        ),
    ]
