# Generated by Django 4.2.6 on 2023-12-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_eventticketcost_category_buyeventticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyeventticket',
            name='category',
            field=models.CharField(choices=[('1', 'GENERAL'), ('2', 'VIP')], max_length=1),
        ),
    ]
